// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadNote(arg1) {
  return window['go']['app']['App']['ReadNote'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['app']['App']['SaveNote'](arg1);
}
