// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ReadNote(arg1:app.Note):Promise<app.Note>;

export function SaveNote(arg1:app.Note):Promise<string>;
