// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}
