// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}
